spring.application.name=mino-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/mino_db
spring.datasource.username=${MINO_DB_USER:postgres}
spring.datasource.password=${MINO_DB_PASSWORD:minodev2026}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

server.port=8081

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

mino.jwt.secret=${MINO_JWT_SECRET:changeme-dev-only-secret-key-please-override-in-prod}
mino.jwt.expiration-ms=604800000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MINO_EMAIL_ADRESSE:changeme@gmail.com}
spring.mail.password=${MINO_EMAIL_MOT_DE_PASSE_APP:changeme}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mino.email.expediteur=${MINO_EMAIL_ADRESSE:changeme@gmail.com}
